#!/usr/bin/env python3
import argparse
from ComicBook import ComicBook
import concurrent.futures
import sys
from lxml import html
import os
import requests
from zipfile import ZipFile

AGENT = 'Mozilla/5.0 (X11; CrOS x86_64 14324.56.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4692.70 Safari/537.36'
HEADERS = {'User-Agent': AGENT}
VERBOSE = False
MESSAGE = """
    _________                _____
    __  ____/____________ ______(_)______
    _  /    _  __ \_  __ `__ \_  /_  ___/
    / /___  / /_/ /  / / / / /  / / /__
    \____/  \____//_/ /_/ /_//_/  \___/

    _____________
    ___  __ \__(_)____________________________
    __  /_/ /_  /___  __ \__  __ \  _ \_  ___/
    _  _, _/_  / __  /_/ /_  /_/ /  __/  /
    /_/ |_| /_/  _  .___/_  .___/\___//_/
                 /_/     /_/
"""


class CrArgumentParser(argparse.ArgumentParser):

    def print_help(self, file=None):
        if file is None:
            file = sys.stdout
        file.write(MESSAGE + '\n')
        super().print_help(file=file)

    def print_usage(self, file=None):
        if file is None:
            file = sys.stdout
        file.write(MESSAGE + '\n')
        super().print_usage(file=file)


def ripComic(comicBook: ComicBook, overwrite: bool, path: str):
    zipFile = os.path.abspath(path) + os.path.sep + '%s.cbz' % comicBook.title
    if os.path.exists(zipFile) and not overwrite:
        print('%s exists, skipping...' % zipFile)
        return

    # no pages means no comic book for you!
    if comicBook.numPages <= 0:
        print('Could not find any pages for %s' % comicBook.title)
        exit()

    # download and zip up the pages
    print('Processing %d pages for %s' % (comicBook.numPages, comicBook.title))

    with ZipFile(zipFile, 'w') as cbz:
        comicBook.fetchPages()
        for page in comicBook.pages:
            if VERBOSE:
                print('Adding %s to %s' % (page.name, zipFile))
            cbz.writestr('%04d.jpg' % page.number, page.image)


if __name__ == '__main__':
    parser = CrArgumentParser(
        description='Download series of comic books from readcomics.ru.')
    parser.add_argument(
        'url',
        type=str,
        nargs=1,
        help='readcomics.ru URL to parse',
    )
    parser.add_argument(
        '-o',
        '--overwrite',
        action='store_true',
        default=False,
        help='overwrite existing files',
    )
    parser.add_argument(
        '-p',
        '--path',
        type=str,
        nargs=1,
        default=None,
        help='path to output to',
    )
    parser.add_argument(
        '-s',
        '--single',
        action='store_true',
        default=False,
        help='process a single comic',
    )
    parser.add_argument(
        '-v',
        '--verbose',
        action='store_true',
        default=False,
        help='verbose output',
    )
    args = parser.parse_args()
    VERBOSE = args.verbose

    comicsUrl = args.url[0]
    path = '' if args.path is None else args.path[0]
    if args.single:
        ripComic(ComicBook.fromUrl(comicsUrl), args.overwrite, path)
    else:
        page = requests.get(comicsUrl)
        tree = html.fromstring(page.content)
        comicUrls = tree.xpath('.//ul[@class="chapters"]/li/h5/a/@href')
        with concurrent.futures.ThreadPoolExecutor() as executor:
            future_to_url = {
                executor.submit(ripComic, ComicBook.fromUrl(comicUrl),
                                args.overwrite, path): comicUrl
                for comicUrl in comicUrls
            }
            for future in concurrent.futures.as_completed(future_to_url):
                comicUrl = future_to_url[future]
                print('%s finished...' % comicUrl)
